/**
 * AdProject builder — converts a completed crawl result + AI-generated scene
 * copy into a ready-to-edit project with a polished default timeline.
 *
 * WHY the builder does NOT derive copy from raw brand data:
 * String manipulation on raw meta descriptions produces generic results that
 * don't reflect what the business actually does. Instead, the AI service
 * (MockScriptGenerationService → real GPT-4) generates all four scene
 * headlines and subtitles from the full brand context. The builder's only job
 * is to place that copy into the right timeline slots at the right times.
 *
 * Ad structure (30 seconds, 4 scenes):
 *   Scene 1 — HOOK       (0 – 7 s):  business name + tagline/hook subtitle
 *   Scene 2 — VALUE      (7 – 15 s): value proposition from AI
 *   Scene 3 — PROOF      (15 – 23 s): differentiators / keywords from AI
 *   Scene 4 — CTA        (23 – 30 s): action-oriented close + domain button
 */

import { v4 as uuidv4 } from 'uuid';
import type { AdProject, AdTimeline, Track, Clip, FontWeight } from '../../types/project';
import type { ExtractedBrandAssets } from '../../types/crawl';
import type { AdSceneCopy } from '../ai/interfaces';

const AD_DURATION = 30;

// Scene boundaries — the image clips run wall-to-wall; text clips are inset
// by TEXT_INSET seconds at each end to avoid colliding with image transitions.
const SCENES = [
  { type: 'hook',  start:  0, end:  7 },
  { type: 'value', start:  7, end: 15 },
  { type: 'proof', start: 15, end: 23 },
  { type: 'cta',   start: 23, end: 30 },
] as const;

const TEXT_INSET = 0.4; // seconds of breathing room at each scene edge

// ── Public API ─────────────────────────────────────────────────────────────

export interface BuildProjectOptions {
  crawlJobId: string;
  brandAssets: ExtractedBrandAssets;
  voiceoverScript: string;
  /** Structured scene copy generated by the AI service — used verbatim. */
  sceneCopy: AdSceneCopy[];
}

export function buildDefaultProject(options: BuildProjectOptions): AdProject {
  const { crawlJobId, brandAssets, voiceoverScript, sceneCopy } = options;
  const projectId = uuidv4();
  const now = Date.now();

  return {
    id: projectId,
    name: `${brandAssets.businessName} — 30s Ad`,
    sourceUrl: brandAssets.sourceUrl,
    crawlJobId,
    brandAssets,
    timeline: buildDefaultTimeline(brandAssets, voiceoverScript, sceneCopy),
    voiceoverScript,
    status: 'ready',
    exportSettings: {
      resolution: '1920x1080',
      aspectRatio: '16:9',
      format: 'mp4',
      fps: 30,
    },
    createdAt: now,
    updatedAt: now,
  };
}

// ── Timeline construction ──────────────────────────────────────────────────

function buildDefaultTimeline(
  assets: ExtractedBrandAssets,
  voiceoverScript: string,
  sceneCopy: AdSceneCopy[],
): AdTimeline {
  return {
    duration: AD_DURATION,
    tracks: [
      buildImagesTrack(assets),
      buildTextTrack(assets, sceneCopy),
      buildVoiceoverTrack(voiceoverScript),
      buildMusicTrack(),
      buildOverlayTrack(assets),
    ],
  };
}

// ── Images track ───────────────────────────────────────────────────────────

function buildImagesTrack(assets: ExtractedBrandAssets): Track {
  // Exclude logos — they belong in the overlay track, not as scene backgrounds.
  // A logo rendered full-bleed looks broken; it should only appear as a badge.
  const pool = assets.images.filter((img) => !img.isLikelyLogo);

  // Fallback: use OG image if the crawler found no scored content images
  if (pool.length === 0 && assets.ogImage) {
    pool.push({
      src: assets.ogImage,
      alt: assets.businessName,
      isLikelyLogo: false,
      qualityScore: 1,
      naturalWidth: 0,
      naturalHeight: 0,
    });
  }

  const clips: Clip[] = [];
  SCENES.forEach((scene, idx) => {
    if (pool.length === 0) return;
    const img = pool[idx % pool.length]!;
    clips.push({
      id:        uuidv4(),
      startTime: scene.start,
      duration:  scene.end - scene.start,
      data: {
        type:       'image' as const,
        src:        img.src,
        alt:        img.alt || assets.businessName,
        transition: idx % 2 === 0 ? ('fade' as const) : ('slide' as const),
        objectFit:  'cover' as const,
      },
    });
  });

  return { id: 'track-images', type: 'images', label: 'Images', clips, muted: false, locked: false };
}

// ── Text track ─────────────────────────────────────────────────────────────
// Uses AI-generated sceneCopy verbatim. Nothing is derived here.

function buildTextTrack(assets: ExtractedBrandAssets, sceneCopy: AdSceneCopy[]): Track {
  const accent = assets.colors.primary ?? '#3B82F6';
  const clips: Clip[] = [];

  SCENES.forEach((scene) => {
    const copy = sceneCopy.find((s) => s.sceneType === scene.type);
    if (!copy) return;

    const sceneStart    = scene.start;
    const sceneDuration = scene.end - scene.start;
    const headlineStart = sceneStart + TEXT_INSET;
    const headlineDur   = sceneDuration - TEXT_INSET * 2;
    const subStart      = headlineStart + 0.45;
    const subDur        = headlineDur   - 0.45;

    // ── Headline ──────────────────────────────────────────────────────────
    const isCta       = scene.type === 'cta';
    const isHook      = scene.type === 'hook';
    const headlineSize: FontWeight = 700;

    clips.push(makeText({
      content:    copy.headline,
      startTime:  headlineStart,
      duration:   headlineDur,
      fontSize:   isHook ? 58 : isCta ? 46 : 38,
      fontWeight: headlineSize,
      color:      '#F1F5F9',
      fontFamily: 'heading',
      y:          isHook ? 40 : isCta ? 38 : 41,
    }));

    // ── Subtitle ──────────────────────────────────────────────────────────
    // Only render if the AI produced a non-empty subtitle
    if (copy.subtitle.trim()) {
      clips.push(makeText({
        content:    copy.subtitle,
        startTime:  subStart,
        duration:   subDur,
        fontSize:   isHook ? 24 : 22,
        fontWeight: 400 as FontWeight,
        color:      isCta ? accent : 'rgba(241,245,249,0.80)',
        fontFamily: isHook ? 'body' : 'body',
        y:          isHook ? 58 : isCta ? 55 : 59,
      }));
    }
  });

  return { id: 'track-text', type: 'text', label: 'Text', clips, muted: false, locked: false };
}

function makeText(opts: {
  content: string; startTime: number; duration: number;
  fontSize: number; fontWeight: FontWeight; color: string;
  fontFamily: 'heading' | 'body'; y: number;
}): Clip {
  return {
    id:        uuidv4(),
    startTime: opts.startTime,
    duration:  opts.duration,
    data: {
      type:       'text' as const,
      content:    opts.content,
      fontSize:   opts.fontSize,
      fontWeight: opts.fontWeight,
      color:      opts.color,
      position:   { x: 50, y: opts.y },
      align:      'center' as const,
      fontFamily: opts.fontFamily,
    },
  };
}

// ── Voiceover track ────────────────────────────────────────────────────────

function buildVoiceoverTrack(script: string): Track {
  return {
    id: 'track-voiceover', type: 'voiceover', label: 'Voiceover',
    clips: [{
      id: uuidv4(), startTime: 0, duration: AD_DURATION,
      data: { type: 'audio' as const, src: null, volume: 1.0, script },
    }],
    muted: false, locked: false,
  };
}

// ── Music track ────────────────────────────────────────────────────────────

function buildMusicTrack(): Track {
  return {
    id: 'track-music', type: 'music', label: 'Background Music',
    clips: [{
      id: uuidv4(), startTime: 0, duration: AD_DURATION,
      data: { type: 'audio' as const, src: '/assets/music/ambient-01.mp3', volume: 0.28, script: null },
    }],
    muted: false, locked: false,
  };
}

// ── Overlay track ──────────────────────────────────────────────────────────

function buildOverlayTrack(assets: ExtractedBrandAssets): Track {
  const clips: Clip[] = [];

  if (assets.logoUrl) {
    clips.push({
      id: uuidv4(), startTime: 0, duration: AD_DURATION,
      data: {
        type: 'overlay' as const, overlayType: 'logo' as const,
        content: assets.logoUrl,
        position: { x: 5, y: 6 }, size: { width: 14, height: 9 }, visible: true,
      },
    });
  }

  // CTA button enters 1 s into the final scene
  clips.push({
    id: uuidv4(), startTime: SCENES[3].start + 1, duration: SCENES[3].end - SCENES[3].start - 1,
    data: {
      type: 'overlay' as const, overlayType: 'cta' as const,
      content: assets.sourceUrl,
      position: { x: 50, y: 83 }, size: { width: 30, height: 8 }, visible: true,
    },
  });

  return { id: 'track-overlay', type: 'overlay', label: 'Overlays', clips, muted: false, locked: false };
}
